Kufar/Models/Country.cs
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Kufar.Models

{
    public class Country
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }


    }
}

Kufar/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Kufar.Models;
using Kufar.ViewModels;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Logging;

namespace Kufar.Controllers
{
    public class CitiesController : Controller
    {
        private readonly AdvertisementDbContext _context;

        private readonly ILogger<AdvertisementsController> _logger;

        public CitiesController(AdvertisementDbContext context, ILogger<AdvertisementsController> logger)
        {
            _context = context;

            _logger = logger;
        }

        [Authorize]
        public async Task<IActionResult> Create(int id)
        {
          
            var result = _context.Cities.Where(city => city.Country != null && city.Country.Id == id).ToList();
            _logger.LogInformation("Юзер запросил создание города для страны у которой id == " + id);

            var citiesViewModel = new CitiesViewModel
            {
                SelectedCountry = _context.Countries.SingleOrDefault(x => x.Id == id),
                Cities = result
            };
               _logger.LogInformation("Юзер запросил создание города для страны у которой id == " + id);
            return View(citiesViewModel);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id, Name")] CitiesViewModel citiesViewModel)
        {
            if (ModelState.IsValid)
            {
                var cities = new City
                {
                    Name = citiesViewModel.Name,
                    Country = _context.Countries.SingleOrDefault(x => x.Id == citiesViewModel.Id)
                };
             
                _context.Add(cities);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index", "Countries");
            }

            return View(citiesViewModel);
        }       
    }
}

Kufar/Controllers/CountriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Kufar.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Kufar.ViewModels;
using Kufar.Services;

namespace Kufar.Controllers
{
    [Authorize]
    public class CountriesController : Controller
    {
        private readonly AdvertisementDbContext _context;

        private readonly ICountryService countryService;

        public CountriesController(AdvertisementDbContext context, ICountryService countryService)
        {
            this.countryService = countryService;
            _context = context;
        }


        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Countries.ToListAsync());
        }
        [Authorize]
        public IActionResult Create()
        {
            return PartialView();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Country country)
        {
            if (ModelState.IsValid)
            {
                _context.Add(country);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }

            return View(country);
        }

        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var country = await _context.Countries
           .SingleOrDefaultAsync(m => m.Id == id);
            DeleteCityViewModel model = new DeleteCityViewModel()
            {
                Id = country.Id,
                Name = country.Name,
                
            };
          
          

            return PartialView(model);
        }

        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int Id, DeleteCityViewModel deleteCityViewModel)
        {

            await countryService.DeleteCountryAsync(Id);

            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        public async Task<JsonResult> Countries()
        {
            var countries = await _context.Countries.ToListAsync();
            return Json(countries);
        }

    }
}

Kufar/Views/Countries/Create.cshtml
@model Kufar.Models.Country

@{
    ViewData["Title"] = "Create";
}
<div class="modal fade" id="add-contact" tabindex="-1" role="dialog" aria-labelledby="addContactLabel" aria-hidden="true">
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h3 class="modal-title" id="addContactLabel">Add country</h3>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form asp-action="Create" method="post">
                <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary" data-save="modal">Save</button>
        </div>
    </div>
</div>
</div>

Kufar/Views/Countries/Delete.cshtml
@model Kufar.ViewModels.DeleteCityViewModel
@{
    Layout = null;
}
<div class="modal-content">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" area-hidden="true">X</button>
        <div>
            <h4>Country</h4>
            <hr />
            <div class="modal-body">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>
                </dl>

                <form asp-action="Delete">
                    <input type="hidden" asp-for="Id" />
                    <input type="submit" value="Delete" class="btn btn-default" /> |
                    <a asp-action="Index">Back</a>
                </form>
            </div>
        </div>
    </div>
</div>

Kufar/Views/Countries/Edit.cshtml
@model Kufar.Models.Country

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Country</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Kufar/Views/Countries/Index.cshtml
@model IEnumerable<Kufar.Models.Country>

@{
    ViewData["Title"] = "Index";
}

<br />
<div id="modal-placeholder"></div>

<button type="button" class="btn btn-primary" data-toggle="ajax-modal" data-target="#add-contact" data-url="@Url.Action("Create")">
    Add Country
</button>
<script>
    $(function () {
        var placeholderElement = $('#modal-placeholder');

        $('button[data-toggle="ajax-modal"]').click(function (event) {
            var url = $(this).data('url');
            $.get(url).done(function (data) {
                placeholderElement.html(data);
                placeholderElement.find('.modal').modal('show');
            });
        });

        placeholderElement.on('click', '[data-save="modal"]', function (event) {
            event.preventDefault();

            var form = $(this).parents('.modal').find('form');
            var actionUrl = form.attr('action');
            var dataToSend = form.serialize();

            $.post(actionUrl, dataToSend).done(function (data) {
                var newBody = $('.modal-body', data);
                placeholderElement.find('.modal-body').replaceWith(newBody);
                var isNotValid = newBody.find('[name="IsValid"]').val() === 'False';
                if (!isNotValid) {
                    placeholderElement.find('.modal').modal('hide');
                    location.reload();
                    
                }
            });
        });
    });
</script>
<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog"></div>
</div>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>

    </tr>
    </thead>
   
    <tbody id="tbody">
        
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-controller="Cities" asp-action="Create"  asp-route-id="@item.Id" >@item.Name</a>
                   
                </td>
                <td>

                    <ul>

                        <li>
                            @Html.ActionLink("Delete", "Delete",
                                new {id = item.Id}, new {@class = "country"})
                        </li>
                    </ul>
                </td>

            </tr>
        }
    </tbody>

</table>

@section scripts
    {
    <script type="text/javascript">

        $(function () {
            $.ajaxSetup({ cache: false });
            $(".country").click(function (e) {

                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })
    </script>
}