Kufar/Controllers/CountriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Kufar.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Kufar.ViewModels;
using Kufar.Services;

namespace Kufar.Controllers
{
    [Authorize]
    public class CountriesController : Controller
    {
        private readonly AdvertisementDbContext _context;

        private readonly ICountryService countryService;

        public CountriesController(AdvertisementDbContext context, ICountryService countryService)
        {
            this.countryService = countryService;
            _context = context;
        }


        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Countries.ToListAsync());
        }
        [Authorize]
        public IActionResult Create()
        {
            return PartialView();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Country country)
        {
            if (ModelState.IsValid)
            {
                _context.Add(country);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }

            return View(country);
        }

        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var country = await _context.Countries
           .SingleOrDefaultAsync(m => m.Id == id);
            DeleteCityViewModel model = new DeleteCityViewModel()
            {
                Id = country.Id,
                Name = country.Name,
                
            };
          
          

            return PartialView(model);
        }

        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int Id, DeleteCityViewModel deleteCityViewModel)
        {

            await countryService.DeleteCountryAsync(Id);

            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        public async Task<JsonResult> Countries()
        {
            var countries = await _context.Countries.ToListAsync();
            return Json(countries);
        }

    }
}

Kufar/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Kufar.Models;
using Kufar.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
namespace Kufar.Controllers
{
    public class UserController : Controller
    {
        readonly UserManager<User> _userManager;

        public UserController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }

        [Authorize]
        public ViewResult Index()
        {
            ViewBag.userManager = _userManager;
            return View(_userManager.Users.ToList());
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Profile()
        {
            var user = await _userManager.GetUserAsync(User);
            var model = new UserViewModel
            {
                Email = user.Email,
                Year = user.Year
            };
            return View(model);
        }
    }
}

Kufar/Views/Shared/_Block.cshtml
@using Kufar.Models
@using Kufar.ViewModels
@model Kufar.ViewModels.IndexViewModel
@addTagHelper "*, Kufar"
<div class="row">
    <div class="col-md-8 col-sm-8">
        @foreach (Advertisement u in Model.Advertisements)
        {
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-2">
                            <div class="thumbnail" style="height: 100px; width:80px">
                                <img id="photo" style="height: 90px; width: 80px" src="@u.Photo">
                            </div>
                        </div>
                        <div class="col-md-10">
                            <h3 style="color:deepskyblue;">@Html.Raw(@u.Title)</h3>
                            <span>
                                <hr />
                               <a asp-action="Index" asp-route-pageNumber="@Model.PageViewModel.PageNumber" asp-route-sortOrder="@Model.SortViewModel.TitleSort">Title</a>
                                <hr />
                            </span>
                            <span>
                                <hr />
                                <h5>@Html.Raw(u.Country?.Name)</h5>
                                <hr />
                            </span>
                            <span>
                                <hr />
                                <h5>@Html.Raw(u.City?.Name)</h5>
                                <hr />
                            </span>
                            <span>
                                <a asp-action="Edit" asp-route-id="@u.Id">Edit</a> |
                                <a asp-action="Details" asp-route-id="@u.Id">Details</a> |
                                <a asp-action="Delete" asp-route-id="@u.Id">Delete</a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Kufar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <title>@ViewData["Title"] - Kufar</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Kufar</a>
            </div>
       
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Context.User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Advertisements" asp-action="Index">Advertisements</a></li>
                        <li><a asp-area="" asp-controller="Countries" asp-action="Index">Add country</a></li>
                        <li><a asp-area="" asp-controller="User" asp-action="Index">User list</a></li>
                        <li>
                    </li>
                            }
                    </ul>
             
                    @await Html.PartialAsync("_LoginPartial")
            @if (Context.User.Identity.IsAuthenticated)
            {
                <div class="language-selector">
                    @await Html.PartialAsync("_SelectLanguagePartial")
                </div>
                
            }
            </div>
        
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        
        <footer class="footer">
            <p>&copy; 2018 - Kufar</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Kufar/Views/Shared/_List.cshtml
@model Kufar.ViewModels.IndexViewModel
@addTagHelper "*, Kufar"
<table class="table">
    <th>Photo</th>
    <th>
        <a asp-action="Index" asp-route-pageNumber="@Model.PageViewModel.PageNumber" asp-route-sortOrder="@Model.SortViewModel.TitleSort">Title</a>
    </th>
    <th>
        <a asp-action="Index" asp-route-pageNumber="@Model.PageViewModel.PageNumber" asp-route-sortOrder="@Model.SortViewModel.DescriptionSort">Description</a>
    </th>
    <th>Country</th>
    <th>City</th>
    <th>Function</th>
    <th>&nbsp;</th>
    @foreach (Advertisement u in Model.Advertisements)
    {
        <tr>
            <td class="thumbnail" style="height: 100px; width: 80px">

                <img id="photo" style="height: 90px; width: 80px" src="@u.Photo">
            <td>@u.Title</td>
            <td>@u.Description @Html.Raw(u.Description)</td>
            <td>@u.Country?.Name</td>
            <td>@u.City?.Name</td>
            <td>
                <a asp-action="Edit" asp-route-id="@u.Id">Edit</a>
                <a asp-action="Details" asp-route-id="@u.Id">Details</a>
                <a asp-action="Delete" asp-route-id="@u.Id">Delete</a>
            </td>

        </tr>
    }

</table>

Kufar/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options
@using Kufar.Models.Enums
@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();

    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}

<form asp-controller="Advertisements" asp-action="SetLanguage"
      asp-route-returnUrl="@Context.Request.Path"
      method="post">
    <div class="col-xs-1">
        <select class="form-control" name="culture" onchange="this.form.submit();"
                asp-for="@requestCulture.RequestCulture.UICulture.Name"
                asp-items="cultureItems"></select>
  
              
    </div>
</form>